#!/bin/bash
set -e
# Requires: gh auth login
gh issue close 551 --comment "Closed: duplicate — already in listings.json."
gh issue close 552 --comment "Closed: duplicate — already in listings.json."
gh issue close 553 --comment "Closed: out of scope."
gh issue close 554 --comment "Closed: duplicate — already in listings.json."
gh issue close 555 --comment "Closed: duplicate — already in listings.json."
gh issue close 556 --comment "Closed: duplicate — already in listings.json."
gh issue close 557 --comment "Closed: duplicate — already in listings.json."
gh issue close 558 --comment "Closed: duplicate — already in listings.json."
gh issue close 559 --comment "Closed: duplicate — already in listings.json."
gh issue close 560 --comment "Closed: duplicate — already in listings.json."
gh issue close 561 --comment "Closed: duplicate — already in listings.json."
gh issue close 562 --comment "Closed: dead application link."
gh issue close 563 --comment "Closed: duplicate — already in listings.json."
gh issue close 564 --comment "Closed: duplicate — already in listings.json."
gh issue close 565 --comment "Closed: duplicate — already in listings.json."
gh issue close 566 --comment "Closed: duplicate — already in listings.json."
gh issue close 568 --comment "Closed: out of scope."
gh issue close 569 --comment "Closed: dead application link."
gh issue close 570 --comment "Closed: dead application link."
gh issue close 571 --comment "Closed: duplicate — already in listings.json."
gh issue close 572 --comment "Closed: duplicate — already in listings.json."
gh issue close 577 --comment "Closed: duplicate — already in listings.json."
gh issue close 578 --comment "Closed: out of scope."
gh issue close 579 --comment "Closed: out of scope."
gh issue close 580 --comment "Closed: out of scope."
gh issue close 581 --comment "Closed: duplicate — already in listings.json."
gh issue close 582 --comment "Closed: dead application link."
gh issue close 583 --comment "Closed: duplicate — already in listings.json."
gh issue close 584 --comment "Closed: duplicate — already in listings.json."
gh issue close 585 --comment "Closed: duplicate — already in listings.json."
gh issue close 586 --comment "Closed: duplicate — already in listings.json."
gh issue close 587 --comment "Closed: duplicate — already in listings.json."
gh issue close 588 --comment "Closed: duplicate — already in listings.json."
gh issue close 589 --comment "Closed: duplicate — already in listings.json."
gh issue close 590 --comment "Closed: duplicate — already in listings.json."
gh issue close 591 --comment "Closed: out of scope."
gh issue close 592 --comment "Closed: out of scope."
gh issue close 593 --comment "Closed: duplicate — already in listings.json."
gh issue close 594 --comment "Closed: duplicate — already in listings.json."
gh issue close 595 --comment "Closed: out of scope."
gh issue close 596 --comment "Closed: out of scope."
gh issue close 597 --comment "Closed: out of scope."
gh issue close 598 --comment "Closed: out of scope."
gh issue close 599 --comment "Closed: duplicate — already in listings.json."
gh issue close 600 --comment "Closed: out of scope."
gh issue close 601 --comment "Closed: out of scope."
gh issue close 602 --comment "Closed: out of scope."
gh issue close 603 --comment "Closed: out of scope."
gh issue close 604 --comment "Closed: out of scope."
gh issue close 605 --comment "Closed: out of scope."
gh issue close 606 --comment "Closed: duplicate — already in listings.json."
gh issue close 607 --comment "Closed: out of scope."
gh issue close 608 --comment "Closed: out of scope."
gh issue close 609 --comment "Closed: out of scope."
gh issue close 610 --comment "Closed: out of scope."
gh issue close 611 --comment "Closed: out of scope."
gh issue close 612 --comment "Closed: duplicate — already in listings.json."
gh issue close 613 --comment "Closed: out of scope."
gh issue close 614 --comment "Closed: duplicate — already in listings.json."
gh issue close 615 --comment "Closed: out of scope."
gh issue close 616 --comment "Closed: out of scope."
gh issue close 617 --comment "Closed: out of scope."
gh issue close 618 --comment "Closed: out of scope."
gh issue close 619 --comment "Closed: out of scope."
gh issue close 620 --comment "Closed: out of scope."
gh issue close 621 --comment "Closed: out of scope."
gh issue close 622 --comment "Closed: out of scope."
gh issue close 624 --comment "Closed: out of scope."
gh issue close 625 --comment "Closed: out of scope."
gh issue close 626 --comment "Closed: out of scope."
gh issue close 627 --comment "Closed: out of scope."
gh issue close 628 --comment "Closed: out of scope."
gh issue close 629 --comment "Closed: out of scope."
gh issue close 630 --comment "Closed: out of scope."
gh issue close 631 --comment "Closed: out of scope."
gh issue close 632 --comment "Closed: out of scope."
gh issue close 633 --comment "Closed: out of scope."
gh issue close 634 --comment "Closed: out of scope."
gh issue close 635 --comment "Closed: duplicate — already in listings.json."
gh issue close 636 --comment "Closed: out of scope."
gh issue close 637 --comment "Closed: out of scope."
gh issue close 638 --comment "Closed: out of scope."
gh issue close 639 --comment "Closed: out of scope."
gh issue close 640 --comment "Closed: out of scope."
gh issue close 641 --comment "Closed: out of scope."
gh issue close 642 --comment "Closed: out of scope."
gh issue close 643 --comment "Closed: duplicate — already in listings.json."
gh issue close 644 --comment "Closed: out of scope."
gh issue close 645 --comment "Closed: duplicate — already in listings.json."
gh issue close 646 --comment "Closed: duplicate — already in listings.json."
gh issue close 647 --comment "Closed: out of scope."
gh issue close 648 --comment "Closed: duplicate — already in listings.json."
gh issue close 649 --comment "Closed: duplicate — already in listings.json."
gh issue close 650 --comment "Closed: duplicate — already in listings.json."
gh issue close 651 --comment "Closed: duplicate — already in listings.json."
gh issue close 652 --comment "Closed: duplicate — already in listings.json."
gh issue close 653 --comment "Closed: duplicate — already in listings.json."
gh issue close 654 --comment "Closed: duplicate — already in listings.json."
gh issue close 655 --comment "Closed: duplicate — already in listings.json."
gh issue close 656 --comment "Closed: duplicate — already in listings.json."
gh issue close 657 --comment "Closed: duplicate — already in listings.json."
gh issue close 658 --comment "Closed: duplicate — already in listings.json."
gh issue close 659 --comment "Closed: duplicate — already in listings.json."
gh issue close 660 --comment "Closed: duplicate — already in listings.json."
gh issue close 661 --comment "Closed: duplicate — already in listings.json."
gh issue close 662 --comment "Closed: duplicate — already in listings.json."
gh issue close 663 --comment "Closed: duplicate — already in listings.json."
gh issue close 664 --comment "Closed: out of scope."
gh issue close 665 --comment "Closed: duplicate — already in listings.json."
gh issue close 666 --comment "Closed: duplicate — already in listings.json."
gh issue close 667 --comment "Closed: duplicate — already in listings.json."
gh issue close 668 --comment "Closed: duplicate — already in listings.json."
gh issue close 669 --comment "Closed: duplicate — already in listings.json."
gh issue close 670 --comment "Closed: out of scope."
gh issue close 671 --comment "Closed: duplicate — already in listings.json."
gh issue close 672 --comment "Closed: duplicate — already in listings.json."
gh issue close 673 --comment "Closed: duplicate — already in listings.json."
gh issue close 674 --comment "Closed: duplicate — already in listings.json."
gh issue close 675 --comment "Closed: duplicate — already in listings.json."
gh issue close 676 --comment "Closed: duplicate — already in listings.json."
gh issue close 677 --comment "Closed: duplicate — already in listings.json."
gh issue close 678 --comment "Closed: duplicate — already in listings.json."
gh issue close 679 --comment "Closed: duplicate — already in listings.json."
gh issue close 680 --comment "Closed: duplicate — already in listings.json."
gh issue close 681 --comment "Closed: duplicate — already in listings.json."
gh issue close 682 --comment "Closed: duplicate — already in listings.json."
gh issue close 683 --comment "Closed: duplicate — already in listings.json."
gh issue close 684 --comment "Closed: duplicate — already in listings.json."
gh issue close 685 --comment "Closed: duplicate — already in listings.json."
gh issue close 686 --comment "Closed: duplicate — already in listings.json."
gh issue close 687 --comment "Closed: duplicate — already in listings.json."
gh issue close 688 --comment "Closed: duplicate — already in listings.json."
gh issue close 689 --comment "Closed: duplicate — already in listings.json."
gh issue close 690 --comment "Closed: duplicate — already in listings.json."
gh issue close 691 --comment "Closed: duplicate — already in listings.json."
gh issue close 692 --comment "Closed: duplicate — already in listings.json."
gh issue close 693 --comment "Closed: duplicate — already in listings.json."
gh issue close 694 --comment "Closed: duplicate — already in listings.json."
gh issue close 695 --comment "Closed: duplicate — already in listings.json."
gh issue close 696 --comment "Closed: duplicate — already in listings.json."
gh issue close 697 --comment "Closed: duplicate — already in listings.json."
gh issue close 698 --comment "Closed: duplicate — already in listings.json."
gh issue close 699 --comment "Closed: duplicate — already in listings.json."
gh issue close 700 --comment "Closed: duplicate — already in listings.json."
gh issue close 701 --comment "Closed: duplicate — already in listings.json."
gh issue close 702 --comment "Closed: duplicate — already in listings.json."
gh issue close 703 --comment "Closed: duplicate — already in listings.json."
gh issue close 704 --comment "Closed: duplicate — already in listings.json."
gh issue close 705 --comment "Closed: duplicate — already in listings.json."
gh issue close 706 --comment "Closed: duplicate — already in listings.json."
gh issue close 707 --comment "Closed: duplicate — already in listings.json."
gh issue close 708 --comment "Closed: duplicate — already in listings.json."
gh issue close 709 --comment "Closed: duplicate — already in listings.json."
gh issue close 710 --comment "Closed: duplicate — already in listings.json."
gh issue close 711 --comment "Closed: duplicate — already in listings.json."
gh issue close 712 --comment "Closed: duplicate — already in listings.json."
gh issue close 713 --comment "Closed: duplicate — already in listings.json."
gh issue close 714 --comment "Closed: duplicate — already in listings.json."
gh issue close 715 --comment "Closed: duplicate — already in listings.json."
gh issue close 716 --comment "Closed: duplicate — already in listings.json."
gh issue close 717 --comment "Closed: duplicate — already in listings.json."
gh issue close 718 --comment "Closed: duplicate — already in listings.json."
gh issue close 719 --comment "Closed: duplicate — already in listings.json."
gh issue close 720 --comment "Closed: duplicate — already in listings.json."
gh issue close 721 --comment "Closed: duplicate — already in listings.json."
gh issue close 722 --comment "Closed: duplicate — already in listings.json."
gh issue close 723 --comment "Closed: duplicate — already in listings.json."
gh issue close 724 --comment "Closed: duplicate — already in listings.json."
gh issue close 725 --comment "Closed: duplicate — already in listings.json."
gh issue close 726 --comment "Closed: duplicate — already in listings.json."
gh issue close 727 --comment "Closed: duplicate — already in listings.json."
gh issue close 728 --comment "Closed: duplicate — already in listings.json."
gh issue close 729 --comment "Closed: duplicate — already in listings.json."
gh issue close 730 --comment "Closed: duplicate — already in listings.json."
gh issue close 731 --comment "Closed: duplicate — already in listings.json."
gh issue close 732 --comment "Closed: duplicate — already in listings.json."
gh issue close 733 --comment "Closed: duplicate — already in listings.json."
gh issue close 734 --comment "Closed: out of scope."
gh issue close 735 --comment "Closed: duplicate — already in listings.json."
gh issue close 736 --comment "Closed: duplicate — already in listings.json."
gh issue close 737 --comment "Closed: duplicate — already in listings.json."
gh issue close 738 --comment "Closed: duplicate — already in listings.json."
gh issue close 739 --comment "Closed: duplicate — already in listings.json."
gh issue close 740 --comment "Closed: out of scope."
gh issue close 742 --comment "Closed: out of scope."
gh issue close 743 --comment "Closed: duplicate — already in listings.json."
gh issue close 744 --comment "Closed: duplicate — already in listings.json."
gh issue close 745 --comment "Closed: duplicate — already in listings.json."
gh issue close 746 --comment "Closed: duplicate — already in listings.json."
gh issue close 747 --comment "Closed: duplicate — already in listings.json."
gh issue close 748 --comment "Closed: duplicate — already in listings.json."
gh issue close 749 --comment "Closed: duplicate — already in listings.json."
gh issue close 750 --comment "Closed: duplicate — already in listings.json."
gh issue close 751 --comment "Closed: duplicate — already in listings.json."
gh issue close 752 --comment "Closed: duplicate — already in listings.json."
gh issue close 753 --comment "Closed: duplicate — already in listings.json."
gh issue close 754 --comment "Closed: duplicate — already in listings.json."
gh issue close 755 --comment "Closed: duplicate — already in listings.json."
gh issue close 756 --comment "Closed: duplicate — already in listings.json."
gh issue close 757 --comment "Closed: duplicate — already in listings.json."
gh issue close 758 --comment "Closed: duplicate — already in listings.json."
gh issue close 759 --comment "Closed: duplicate — already in listings.json."
gh issue close 760 --comment "Closed: duplicate — already in listings.json."
gh issue close 761 --comment "Closed: duplicate — already in listings.json."
gh issue close 762 --comment "Closed: duplicate — already in listings.json."
gh issue close 763 --comment "Closed: duplicate — already in listings.json."
gh issue close 764 --comment "Closed: duplicate — already in listings.json."
gh issue close 765 --comment "Closed: duplicate — already in listings.json."
gh issue close 766 --comment "Closed: dead application link."
gh issue close 767 --comment "Closed: dead application link."
gh issue close 768 --comment "Closed: duplicate — already in listings.json."
gh issue close 769 --comment "Closed: duplicate — already in listings.json."
gh issue close 770 --comment "Closed: duplicate — already in listings.json."
gh issue close 771 --comment "Closed: duplicate — already in listings.json."
gh issue close 772 --comment "Closed: duplicate — already in listings.json."
gh issue close 773 --comment "Closed: duplicate — already in listings.json."
gh issue close 774 --comment "Closed: out of scope."
gh issue close 775 --comment "Closed: out of scope."
gh issue close 776 --comment "Closed: out of scope."
gh issue close 777 --comment "Closed: out of scope."
gh issue close 778 --comment "Closed: duplicate — already in listings.json."
gh issue close 779 --comment "Closed: out of scope."
gh issue close 780 --comment "Closed: out of scope."
gh issue close 781 --comment "Closed: out of scope."
gh issue close 782 --comment "Closed: out of scope."
gh issue close 783 --comment "Closed: duplicate — already in listings.json."
gh issue close 784 --comment "Closed: out of scope."
gh issue close 785 --comment "Closed: duplicate — already in listings.json."
gh issue close 788 --comment "Closed: out of scope."
gh issue close 789 --comment "Closed: out of scope."
gh issue close 790 --comment "Closed: duplicate — already in listings.json."
gh issue close 792 --comment "Closed: out of scope."
gh issue close 793 --comment "Closed: duplicate — already in listings.json."
gh issue close 796 --comment "Closed: duplicate — already in listings.json."
gh issue close 797 --comment "Closed: duplicate — already in listings.json."
gh issue close 798 --comment "Closed: duplicate — already in listings.json."
gh issue close 799 --comment "Closed: duplicate — already in listings.json."
gh issue close 800 --comment "Closed: out of scope."
gh issue close 801 --comment "Closed: duplicate — already in listings.json."
gh issue close 802 --comment "Closed: duplicate — already in listings.json."
gh issue close 803 --comment "Closed: duplicate — already in listings.json."
gh issue close 804 --comment "Closed: duplicate — already in listings.json."
gh issue close 805 --comment "Closed: out of scope."
gh issue close 806 --comment "Closed: duplicate — already in listings.json."
gh issue close 807 --comment "Closed: duplicate — already in listings.json."
gh issue close 808 --comment "Closed: duplicate — already in listings.json."
gh issue close 809 --comment "Closed: out of scope."
gh issue close 810 --comment "Closed: duplicate — already in listings.json."
gh issue close 811 --comment "Closed: duplicate — already in listings.json."
gh issue close 812 --comment "Closed: duplicate — already in listings.json."
gh issue close 813 --comment "Closed: duplicate — already in listings.json."
gh issue close 814 --comment "Closed: duplicate — already in listings.json."
gh issue close 815 --comment "Closed: duplicate — already in listings.json."
gh issue close 816 --comment "Closed: duplicate — already in listings.json."
gh issue close 817 --comment "Closed: duplicate — already in listings.json."
gh issue close 825 --comment "Closed: duplicate — already in listings.json."
gh issue close 826 --comment "Closed: duplicate — already in listings.json."
gh issue close 827 --comment "Closed: out of scope."
gh issue close 829 --comment "Closed: out of scope."
gh issue close 830 --comment "Closed: out of scope."
gh issue close 831 --comment "Closed: out of scope."
gh issue close 832 --comment "Closed: duplicate — already in listings.json."
gh issue close 833 --comment "Closed: duplicate — already in listings.json."
gh issue close 834 --comment "Closed: duplicate — already in listings.json."
gh issue close 835 --comment "Closed: duplicate — already in listings.json."
gh issue close 836 --comment "Closed: duplicate — already in listings.json."
gh issue close 838 --comment "Closed: out of scope."
gh issue close 839 --comment "Closed: duplicate — already in listings.json."
gh issue close 840 --comment "Closed: duplicate — already in listings.json."
gh issue close 841 --comment "Closed: duplicate — already in listings.json."
gh issue close 842 --comment "Closed: duplicate — already in listings.json."
gh issue close 843 --comment "Closed: duplicate — already in listings.json."
gh issue close 844 --comment "Closed: duplicate — already in listings.json."
gh issue close 845 --comment "Closed: duplicate — already in listings.json."
gh issue close 846 --comment "Closed: duplicate — already in listings.json."
gh issue close 847 --comment "Closed: duplicate — already in listings.json."
gh issue close 851 --comment "Closed: duplicate — already in listings.json."
gh issue close 852 --comment "Closed: duplicate — already in listings.json."
gh issue close 853 --comment "Closed: duplicate — already in listings.json."
gh issue close 854 --comment "Closed: duplicate — already in listings.json."
gh issue close 855 --comment "Closed: duplicate — already in listings.json."
gh issue close 858 --comment "Closed: out of scope."
gh issue close 859 --comment "Closed: duplicate — already in listings.json."
gh issue close 860 --comment "Closed: out of scope."
gh issue close 861 --comment "Closed: duplicate — already in listings.json."
gh issue close 862 --comment "Closed: duplicate — already in listings.json."
gh issue close 864 --comment "Closed: duplicate — already in listings.json."
gh issue close 865 --comment "Closed: duplicate — already in listings.json."
gh issue close 868 --comment "Closed: duplicate — already in listings.json."
gh issue close 869 --comment "Closed: out of scope."
gh issue close 870 --comment "Closed: duplicate — already in listings.json."
